version: "3.9"

services:
  db:
    image: postgres:12-alpine
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: bangkit_123
      POSTGRES_DB: hydroponic_monitoring
    volumes:
      - hydroponic_monitoring_pgsql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  node_backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/node_backend
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  hydroponic_monitoring_pgsql:
